import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { PrismaClient } from "@prisma/client";
import { ProtocolEngine } from "../../modules/agent/protocol/protocol-engine.js";
import { PricingService } from "../../modules/revenue/pricing-service.js";
import { RazorpayProvider } from "../../infrastructure/razorpay/razorpay.provider.js";
import { DecisionLogger } from "../../modules/audit/decision-logger.js";
import { env } from "../../config/env.js";
import { mcpTools } from "./contract.js";

// Initialize Dependencies
const prisma = new PrismaClient();
const decisionLogger = new DecisionLogger(prisma);
const pricingService = new PricingService(prisma);
const paymentProvider = new RazorpayProvider(env.providers.razorpayKeyId || '', env.providers.razorpayKeySecret || '');
const protocolEngine = new ProtocolEngine(prisma, pricingService, paymentProvider, decisionLogger);

// Initialize MCP Server
const server = new McpServer({
  name: "Agentic Commerce Merchant MCP",
  version: "1.0.0"
});

// Helper to find the correct tool description from the contract
const getDesc = (name: string) => mcpTools.find(t => t.name === name)?.description || '';

// 1. Tool: merchant.commerce.request
server.tool(
  "merchant.commerce.request",
  getDesc("merchant.commerce.request"),
  {
    merchantId: z.string().describe("The ID of the merchant to query"),
    query: z.string().describe("The buyer's request (e.g., 'Find me 10 laptops under 10 lakh')")
  },
  async ({ merchantId, query }) => {
    try {
      let actualMerchantId = merchantId;
      if (merchantId === 'agentic_electronics') {
        const firstMerchant = await prisma.merchant.findFirst();
        if (firstMerchant) actualMerchantId = firstMerchant.id;
      }

      // Dynamically fetch the first two products from the database for this merchant
      // (This simulates an LLM understanding the query and picking the right products)
      const products = await prisma.product.findMany({
        where: { merchantId: actualMerchantId },
        take: 2
      });
      
      if (products.length === 0) {
        throw new Error(`No products found for merchant ${actualMerchantId}`);
      }
      
      const items = products.map(p => ({
        productId: p.id,
        name: p.name,
        quantity: 10,
        unitPriceMinor: p.priceMinor
      }));
      
      const offer = await protocolEngine.createOffer(actualMerchantId, 'buyer_mcp_123', 'session_mcp_123', items, 0);
      
      return {
        content: [{ 
          type: "text", 
          text: `Offer generated by Merchant PolicyEngine:\nID: ${offer.id}\nSubtotal: ₹${offer.subtotalMinor / 100}\nTotal: ₹${offer.totalMinor / 100}\nNote: Prices are non-negotiable via this tool.` 
        }]
      };
    } catch (e: any) {
      return { content: [{ type: "text", text: `Error: ${e.message}` }] };
    }
  }
);

// 2. Tool: merchant.offer.counter
server.tool(
  "merchant.offer.counter",
  getDesc("merchant.offer.counter"),
  {
    offerId: z.string().describe("The ID of the current offer being negotiated"),
    requestedTotalAmount: z.number().describe("The total amount the buyer is proposing in standard currency units (e.g. 100 for ₹100)")
  },
  async ({ offerId, requestedTotalAmount }) => {
    try {
      // Find the offer first to get the correct merchant ID
      const existingOffer = await prisma.offer.findUnique({ where: { id: offerId } });
      if (!existingOffer) {
        throw new Error(`Offer not found: ${offerId}`);
      }

      const offer = await protocolEngine.counterOffer(offerId, existingOffer.merchantId, requestedTotalAmount * 100);
      
      return {
        content: [{ 
          type: "text", 
          text: `Counter-offer processed.\nNew Total: ₹${offer.totalMinor / 100}\nStatus: ${offer.status}` 
        }]
      };
    } catch (e: any) {
      return { content: [{ type: "text", text: `Error: ${e.message}` }] };
    }
  }
);

// 3. Tool: merchant.offer.accept
server.tool(
  "merchant.offer.accept",
  getDesc("merchant.offer.accept"),
  {
    offerId: z.string().describe("The ID of the offer being accepted")
  },
  async ({ offerId }) => {
    try {
      const result = await protocolEngine.acceptOffer(offerId, 'buyer_mcp_123');
      
      return {
        content: [{ 
          type: "text", 
          text: `Offer accepted!\nStatus: PAYMENT_PENDING\nPayment Link: ${result.paymentUrl}` 
        }]
      };
    } catch (e: any) {
      return { content: [{ type: "text", text: `Error: ${e.message}` }] };
    }
  }
);

export async function runMcpServer() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.log("Agentic Commerce MCP Server running on Stdio");
}
