import { PrismaClient } from '@prisma/client';
import { ResendEmailProvider } from '../../infrastructure/resend/resend.provider.js';

export class PaymentLinkEmailService {
  private emailProvider: ResendEmailProvider;

  constructor(private prisma: PrismaClient) {
    this.emailProvider = new ResendEmailProvider();
  }

  async sendPaymentRequiredEmail(offerId: string, email: string, paymentLink: string, amountMinor: number, currency: string) {
    const idempotencyKey = `email_payment_${offerId}`;
    
    // Check idempotency
    const existing = await this.prisma.idempotencyRecord.findUnique({
      where: {
        scope_idempotencyKey: {
          scope: 'payment_email',
          idempotencyKey
        }
      }
    });

    if (existing && existing.status === 'COMPLETED') {
      console.log(`[PaymentLinkEmailService] Email already sent for offer ${offerId}`);
      return;
    }

    if (!existing) {
      await this.prisma.idempotencyRecord.create({
        data: {
          idempotencyKey,
          scope: 'payment_email',
          requestFingerprint: offerId,
          status: 'PENDING'
        }
      });
    }

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Negotiated Offer Ready</title>
</head>

<body style="
  margin: 0;
  padding: 0;
  background: #f6f7f9;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
  color: #1f2937;
">

  <div style="
    max-width: 600px;
    margin: 40px auto;
    padding: 0 20px;
  ">

    <!-- Header -->
    <div style="
      background: #111827;
      padding: 24px 28px;
      border-radius: 14px 14px 0 0;
      color: #ffffff;
    ">
      <div style="
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.5px;
        opacity: 0.75;
        margin-bottom: 8px;
      ">
        AGENTIC COMMERCE
      </div>

      <div style="
        font-size: 24px;
        font-weight: 700;
      ">
        Your negotiated offer is ready
      </div>
    </div>

    <!-- Main Card -->
    <div style="
      background: #ffffff;
      padding: 32px 28px;
      border-radius: 0 0 14px 14px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.06);
    ">

      <p style="
        margin: 0 0 24px;
        font-size: 16px;
        line-height: 1.6;
        color: #4b5563;
      ">
        Your AI shopping agent has finished negotiating with the
        merchant. The order is ready for your review and payment.
      </p>

      <!-- Amount -->
      <div style="
        background: #f3f4f6;
        border-radius: 12px;
        padding: 22px;
        margin-bottom: 24px;
        text-align: center;
      ">
        <div style="
          font-size: 13px;
          color: #6b7280;
          margin-bottom: 6px;
        ">
          TOTAL TO PAY
        </div>

        <div style="
          font-size: 32px;
          font-weight: 700;
          color: #111827;
        ">
          ${currency} ${(amountMinor / 100).toLocaleString('en-IN')}
        </div>
      </div>

      <!-- Payment Boundary -->
      <div style="
        border: 1px solid #e5e7eb;
        border-radius: 10px;
        padding: 16px;
        margin-bottom: 26px;
      ">
        <div style="
          font-size: 14px;
          font-weight: 600;
          color: #111827;
          margin-bottom: 6px;
        ">
          Human approval required
        </div>

        <div style="
          font-size: 13px;
          line-height: 1.5;
          color: #6b7280;
        ">
          No payment has been made yet. Review your order and
          choose whether to complete the payment securely through Razorpay.
        </div>
      </div>

      <!-- CTA -->
      <div style="text-align: center; margin: 30px 0;">
        <a
          href="${paymentLink}"
          style="
            display: inline-block;
            padding: 14px 32px;
            background: #2563eb;
            color: #ffffff;
            text-decoration: none;
            font-size: 15px;
            font-weight: 600;
            border-radius: 8px;
          "
        >
          Review &amp; Pay
        </a>
      </div>

      <p style="
        margin: 0;
        text-align: center;
        font-size: 12px;
        color: #9ca3af;
        line-height: 1.5;
      ">
        Payments are securely processed by Razorpay.
      </p>

      <div style="
        height: 1px;
        background: #e5e7eb;
        margin: 28px 0;
      "></div>

      <p style="
        margin: 0;
        font-size: 12px;
        line-height: 1.5;
        color: #9ca3af;
        text-align: center;
      ">
        This email was generated by your merchant's Agentic Commerce system.
      </p>

    </div>
  </div>

</body>
</html>
`;

    try {
      const messageId = await this.emailProvider.sendEmail(email, 'Negotiated Offer Ready — Payment Required', html);
      
      await this.prisma.idempotencyRecord.update({
        where: { scope_idempotencyKey: { scope: 'payment_email', idempotencyKey } },
        data: {
          status: 'COMPLETED',
          result: { messageId },
          completedAt: new Date()
        }
      });

      console.log(`[PaymentLinkEmailService] Successfully sent payment email to ${email} (Message ID: ${messageId})`);
    } catch (e: any) {
      await this.prisma.idempotencyRecord.update({
        where: { scope_idempotencyKey: { scope: 'payment_email', idempotencyKey } },
        data: {
          status: 'FAILED',
          error: { message: e.message }
        }
      });
      throw e;
    }
  }
}
